### ISSUE TITLE
State of the research

### ISSUE THREAD

**Issue by romansavrulin** [featherbear/presonus-studiolive-api#1]
Hello! What's the current state of protocol research?

I'm digging RML16AI family devices and want to know how to control them.

Take a look at [my repo](https://github.com/DjFix/Presonus-RM-RML-Analysis), if you interested

**Comment by featherbear** [comment]
Hey @romansavrulin 

This project is in very early infancy, and I have no intentions to active research the protocol to completeness.
I have only implemented the protocol implementations as per my personal requirements

(Also sorry for the one year reply delay)

**Comment by paco3346** [comment]
I too have started looking at the protocol. In particular I'm looking for anything that's involved in the functionality of the Qmix app. My end goal is to re-create a hardware version of the Qmix app using some ESP32 boards and scribble strips.
