### ISSUE TITLE
Main Channel

### ISSUE THREAD

**Issue by featherbear** [featherbear/presonus-studiolive-api#26]
The main fader value doesn't get sent as a PV, only in `MS`

```
5543000173004d53650068006664727300001d009795ffff0000ffff000034030203ce02b002000000000000000000000000000000000000000000000000000000000000e3bde3bd0000000099990700000000100001001000010002001100020003001300010004001400060005001a00020007001c000100
```

**Comment by featherbear** [comment]
We change the values of normal faders through the PV dca volume, but main is sent with all other values.
Maybe we can also send the PV dca for the main?

**Comment by featherbear** [comment]
TODO: Check ZB payload to see if it contains a key for the main fader

**Comment by deathtrapdan** [comment]
Sounds like some great new work happening on this cool project!
If anyone can figure out how to control the aux/fx faders that would be really nice.
Using a midi controller to send route tracks during a performance to reverb and delay effects on the fly, would be sweet.
Great to see the project getting some love.


________________________________

**Comment by featherbear** [comment]
@deathtrapdan  Oh gosh I am so sorry with the notification spam HAHA

Control over the FX and auxes will definitely be part of the roadmap :)

@fis-cz seems to be developing [MidiMix](https://github.com/atomsoftwarestudios/MidiMix), that will likely supersede my [presonus-studiolive-api-midi-integration](https://github.com/featherbear/presonus-studiolive-api-midi-integration).

---

@fis-cz will you be planning on supporting devices other than the X-Touch Compact?
My project works with the X-Touch Mini. I was planning on forking out money on an X-Touch Compact, or the X-Touch (full), or the PreSonus FaderPort - though I was hesitant because I was not sure of its interoperability [*\*cough and also money\**]

**Comment by deathtrapdan** [comment]
No worries Andrew. As I say, glad to see the project getting attention.

@fiz-cz I managed to run it and it saw my Arturia Keystep Pro.
Once I configured that to match the same channels and CC numbers as Andrews code, I was able to control the mix faders on my 16R perfectly with the Kstep Pro.


________________________________

**Comment by featherbear** [comment]
> We change the values of normal faders through the PV dca volume, but main is sent with all other values. Maybe we can also send the PV dca for the main?

Try: `main/ch1/volume`

https://github.com/featherbear/presonus-studiolive-api/blob/91b1646eabb60201aedc74a41fec6dd92fae89fd/dumps/zlib.parsed#L9919

**Comment by fis-cz** [comment]
Basically, I am writing in the way that anything on the "desk" will be controllable from any controller (keyboard, mouse, MIDI). Also, MIDI feedback will be supported (i.e. faders will move, displays will show channel names, buttons will be color backlighted...), but as I own only X-Touch Compact and APC 40 MK II I will be able to do testing only on these two - no plans to buy another controller. 

I am still thinking how to write the UI  properly and universally so anybody can adjust it to his needs. I think that the best way will be following the  idea implemented in the QLC (free DMX lightning software), where the virtual console can be (must be) designed by user then the virtual console controls can be mapped to whatever controller (DMX channel, MIDI channel...). It will definitely take some time and the first version will be mainly for the X-Touch Compact without possibility to design the UI by user.

Regarding the features, my plan is to implement just the control functions (controlling buttons, knobs and faders), not any programming functions, scene management, file management and others. Maybe some functions for SD recording / playing will be done, but as I don't use this at all (I am recording / playing through AVB), this will be the last part.

So the use case is to setup the mixer through the UC Surface completely (channel setup, naming, coloring, whatever) then controlling it through the MIDI controller (when we mix live, we usually need just gain, eq, compressor, gate, mixes with their masters, fx control, fx tempo tapping and talkback button).

Regarding technologies, I am still not also sure it should be the Electron app as my plan is to build a suitcase with some small computer (such as RPi) and Electron app is bit hungry for such small platforms. Moreover, currently its React on the frontend side and is not great in performance for "graphical" UI's so I will probably rewrite it to something more reliable  (such as Svelte). 

The first version will be definitely an Electron / React, X-Touch Compact, there will not be a MIDI profile editor as well as there will not be a feature mapping editor (these will be done through JSON or built-in JS Objects only).

For these features I need to be able to control whatever channel and mix, hopefully with all features it allows (gain, gate, eq, compressor). Bonus is control of FXs (at least the tap function should be working) and control of graphical EQ through faders. I don't plan to support switching of the phantom, joining channels to stereo, phase inversion - these are mixer configurations what has to be done through UC.

Unfortunately, I am ultra busy for next two weeks with work, family, preparation of festival, practicing drums and tons of other tasks so unfortunately, I can't work in this. Just check the web I did for our fest, its funny ;) www.conjunction.cz

**Comment by featherbear** [comment]
Very cute website! Not sure how I am listening to stereo though when the plug is only TS 🤣!

Thanks for sharing your project plan, seems useful and offers room for further development down the line

If you're just relaying between the console and your MIDI controller, then you probably don't need an Electron frontend? I assume it should be able to run headless - my implementation serves a webpage so the client computer can deal with all the graphical rendering.

**Comment by fis-cz** [comment]
> Very cute website! Not sure how I am listening to stereo though when the plug iw
> Thanks for sharing your project plan, seems useful and offers room for further development down the line
> 
> If you're just relaying between the console and your MIDI controller, then you probably don't need an Electron frontend? I assume it should be able to run headless - my implementation serves a webpage so the client computer can deal with all the graphical rendering.

**Comment by fis-cz** [comment]
😃 Thanks. It is a magic - it is stereo Jack 🙃

We definitely need some UI because of paging and mixes switching. As we can’t synchronize UC control view, we need our own. Otherwise you will have no idea what you are controlling. There are just 8+1 channels on the  X-Touch so there must be some mechanism to be possible to control “everything” as in case of “adult” mixers.

It does not matter so much, if the data will be transferred over messaging or API+WebSockets so the frontend can also be a normal SPA app (which can be later separated from the Electron).

However, if Electron consumes a lot of resources, Node.js web server and  full browser it will be bit worse for small platforms. And to be honest I would not like to carry another computer to gigs :) Can you share your use cases for this complete project? I have seen you just wanted to control mute and volume for few channels. Is this still valid?

I think that the best way will be to finish the multiplatform Electron version then eventually (relatively simply) migrate to the client/server architecture.
