### ISSUE TITLE
Bug: Volume level percentage sometimes between 0-1 and sometimes between 0-100

### ISSUE THREAD

**Issue by Akkjon** [featherbear/presonus-studiolive-api#36]
Hi,
there seems to be a bug somewhere in the state CacheProvider.
when you call `client.state.get("aux.ch1.volume")` e.g. on a fader value, by default, a percentage between 0-1 is returned, if a fader is moved tho, this value range changes to 0-100 which makes the value unpredictable.

Steps to reproduce:
- connect to the mixer, get the state of "aux.ch1.volume", should return something in the range of 0-1
- move the volume slider
- call the same state again, now it is between 0-100

There seems to be missing a *100 or /100 somewhere in the library, maybe you know where.
Or is this a known problem by the Presonus api?

**Comment by featherbear** [comment]
Should be fixed in a0f46827d06f485dbc77f577e17ef611a1ade8df  for Aux, FX sends, FX returns and the Main fader

**Comment by featherbear** [comment]
Closed for now as I believe I've fixed it, feel free to reopon this issue or start a new one if I've missed something
